### ISSUE TITLE
Runtime agnostic

### ISSUE THREAD

**Issue by Miaxos** [drmingdrmer/async-entry#1]
Would you allow some work over a PR to have an agnostic runtime?

It would be helpful to be able to write test that could be run against multiple runtime. (Especially in `openraft` which use this library to execute integration test).

I would love to be able to run integration tests with a `monoio` here: https://github.com/datafuselabs/openraft/issues/1011

**Comment by drmingdrmer** [comment]
Hmm... It's feasible.

**Comment by drmingdrmer** [comment]
with `features = ["monoio"]`, monoio support is added in 0.3.3:
https://github.com/drmingdrmer/async-entry/blob/36c2bfe1bdaf684e114317a4d2b05ca66816dab9/async-entry/tests/test_rt.rs#L6-L22

Feel free to reopen this issue if there are any problem.

**Comment by drmingdrmer** [comment]
Refer to: https://docs.rs/async-entry/latest/async_entry/attr.test.html#usage-for-monoio-runtime

<blockquote><div><strong><a href="https://docs.rs/async-entry/latest/async_entry/attr.test.html#usage-for-monoio-runtime">test in async_entry - Rust</a></strong></div><div>Marks async function to be executed by async runtime, suitable to test environment</div></blockquote>

**Comment by Miaxos** [comment]
You're really fast, I was going to take some time to do it this week, I'm back from my weekend & it's all done already! Nice, thank you!
